name: erudaxis
description: "A new Flutter project."
publish_to: 'none'
version: 1.3.4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  dio: ^5.8.0+1
  loader_overlay: ^4.0.4+1
  shared_preferences: ^2.3.3
  jwt_decoder: ^2.0.1
  scroll_to_hide: ^2.2.0
  material_symbols_icons: ^4.2815.1
  shimmer: ^3.0.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  permission_handler: ^11.3.1
  device_info_plus: ^11.3.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  page_transition: ^2.1.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_notification_channel: ^3.1.1
  vibration: ^3.1.3
  flutter_svg: ^2.1.0
  timeago: ^3.7.1
  cached_video_player_plus: ^3.0.3
  flutter_cached_pdfview: ^0.4.3
  jitsi_meet_flutter_sdk: ^11.4.0
  image_cropper: ^9.1.0
  excel: ^4.0.6
  archive: ^3.6.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/images/logo/
flutter_intl:
  enabled: true
