name: Flutter Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'  

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release
