name: Flutter Build

on:
  push:
    branches: [ "main" ]

env:
  SERVER_URL: https://staging-backend.erudaxis.com
  REPO_OWNER: proservices-tc
  REPO_NAME: Erudaxis-mobile
  GITHUB_RELEASE: https://api.github.com/repos/proservices-tc/Erudaxis-mobile/releases/latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate .env file
        run: |
          echo "SERVER_URL=${{ env.SERVER_URL }}" > .env
          echo "REPO_OWNER=${{ env.REPO_OWNER }}" >> .env
          echo "REPO_NAME=${{ env.REPO_NAME }}" >> .env
          echo "GITHUB_TOKEN=${{ secrets.ERUDAXIS_TOKEN }}" >> .env

      - name: Build release APK
        run: flutter build apk --release
