name: Dart
# on:
#   release:
#     types: [published]
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Install dependencies
        run: dart pub get
      - name: build release
        run: flutter  build apk --release
